### ISSUE TITLE
Migration error >= 1.26.4

### ISSUE THREAD

**Issue by YC** [muety/wakapi#177]
Database Engine: sqlite

On 1.26.4
```
2021-04-18T03:36:50.879195765Z [INFO ] potentially running migration '20201103-rename_language_mappings_table'
2021-04-18T03:36:50.907514853Z [INFO ] potentially running migration '20201106-migration_cascade_constraints'
2021-04-18T03:36:50.907545161Z [INFO ] not attempting to drop and regenerate constraints on sqlite
2021-04-18T03:36:50.907548256Z [INFO ] potentially running migration '20210202-fix_cascade_for_alias_user_constraint'
2021-04-18T03:36:50.907551532Z [INFO ] not attempting to drop and regenerate constraints on sqlite
2021-04-18T03:36:50.943274498Z [ERROR] table heartbeats already exists
panic: table heartbeats already exists

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc0000a60a8, 0xc0001ff640, 0x1f, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/standard_formatter.go:57 +0xc5
github.com/emvi/logbuch.(*Logger).Fatal(0xc0000f2000, 0xc0001ff640, 0x1f, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/logger.go:132 +0xb3
github.com/emvi/logbuch.Fatal(...)
	/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/funcs.go:55
github.com/muety/wakapi/migrations.RunSchemaMigrations(0xc0001e9a10, 0xc0000c9680)
	/src/migrations/migrations.go:39 +0x9e
github.com/muety/wakapi/migrations.Run(0xc0001e9a10, 0xc0000c9680)
	/src/migrations/migrations.go:33 +0x4d
main.main()
	/src/main.go:130 +0x389
```

On 1.26.3
```
2021-04-18T03:35:35.216092946Z [INFO ] potentially running migration '20201103-rename_language_mappings_table'
2021-04-18T03:35:35.217842192Z [INFO ] potentially running migration '20201106-migration_cascade_constraints'
2021-04-18T03:35:35.217855567Z [INFO ] not attempting to drop and regenerate constraints on sqlite
2021-04-18T03:35:35.217858232Z [INFO ] potentially running migration '20210202-fix_cascade_for_alias_user_constraint'
2021-04-18T03:35:35.217861227Z [INFO ] not attempting to drop and regenerate constraints on sqlite
2021-04-18T03:35:35.323460299Z [INFO ] potentially running migration '20210206_drop_badges_column_add_sharing_flags'
2021-04-18T03:35:35.323862156Z [INFO ] not attempting to drop column 'badges_enabled' on sqlite
2021-04-18T03:35:35.323900598Z [INFO ] potentially running migration '20210213-add_has_data_field'
2021-04-18T03:35:35.324017018Z [INFO ] no need to migrate '20210213-add_has_data_field'
2021-04-18T03:35:35.324052575Z [INFO ] potentially running migration '20210221-add_created_date_column'
2021-04-18T03:35:35.324143636Z [INFO ] no need to migrate '20210221-add_created_date_column'
2021-04-18T03:35:35.324177941Z [INFO ] potentially running migration '20210411-add_imprint_content'
2021-04-18T03:35:35.324266939Z [INFO ] no need to migrate '20210411-add_imprint_content'
2021-04-18T03:35:35.324300622Z [INFO ] potentially running migration '20210411-drop_migrations_table'
2021-04-18T03:35:35.324520557Z [INFO ] generating summaries
2021-04-18T03:35:35.327221305Z [INFO ] --> Listening for HTTP on 0.0.0.0:3000... ✅
2021-04-18T03:35:35.632765074Z [INFO ] successfully counted total for user yc
```

**Comment by muety** [comment]
Sorry for the inconveniences! I started to investigate this. First, I can't reproduce it locally. Also, nothing has changed to the heartbeats schema recently.

My assumption is that your heartbeats table already didn't get a schema change quite some time ago. This is likely as some schema migrations just can't be run on SQLite, because it doesn't support altering columns of existing table ([here](https://github.com/muety/wakapi/blob/ed35e7b82d5292e4277652813f6cacaf95fab868/migrations/20201106_migration_cascade_constraints.go#L21)'s an example, with a different table though). Consequently, the auto-migrator tried to apply that change every time you restarted your instance since then, but just failed silently before [this recent change](https://github.com/muety/wakapi/commit/f8e1453754d1d5b6a067a9c425771c653cce64a7) that made migration failures explicit.

Could you please do me a favor and post the output of the following two SQLite statements?

```sql
SELECT name, sql FROM sqlite_master WHERE tbl_name = 'heartbeats';
```

```sql
pragma index_list('heartbeats');
```

**Comment by YC** [comment]
I had an issue with my VM yesterday, which caused corruption to the wakapi database.
What I did this morning was to dump the database, rename the heartbeats table, then the table was regenerated by wakapi and I copied the heartbeat rows over. I believe I did this due to a migration error. 
I think I've probably strayed far from the intended upgrade path (which I should have realised before opening this issue), so I'll try to fix it when I get more free time. 
Sorry for taking up your time.

**Comment by muety** [comment]
Keep me posted if you're still having problems.

Btw., would you be willing to migrate from SQLite to MySQL if a smooth migration script was provided or you using SQLite intentionally, e.g. because of hardware constraints or so? 

I'm still in the dilemma that on the one hand I'd like to drop SQLite support due to all those constraints, but on the other hand want to keep it to ensure a more or less one-click setup. However, I'm thinking of at least providing a convenient way to migrate away from it for advanced, long-term users like you are. What do you think?

**Comment by YC** [comment]
I managed to upgrade to the latest version, by copying over rows and swapping the time and machine columns (which were in different orders after `insert into heartbeats select * from old.heartbeats`). Hopefully it's all good now and doesn't present more issues for me in the future. 
I think there is a bug with generating/regenerating summaries by clicking the button and/or visiting all time summary page multiple times. I somehow ended up with 3x the time, which I fixed by dropping the summary tables and letting it regenerate. 

Regarding database, I'm currently using SQLite due to memory constraints. 
Regardless of whether there are memory constraints, I'd still prefer a lightweight database from the admin perspective, as I'd have to run a separate Docker container otherwise. 
That being said, I'm willing to migrate if SQLite support is dropped. 
I'm not sure whether there is demand for migration script. Perhaps you can open an issue and ask people to upvote if they want a migration script?

**Comment by muety** [comment]
> I think there is a bug with generating/regenerating summaries by clicking the button and/or visiting all time summary page multiple times. I somehow ended up with 3x the time

Indeed, there currently is no soft or hard check to prevent overlapping summaries. In theory, you could have two summaries for the same day and they would be added up in `mergeSummaries()`. I'll open a new issue and take a look soon. However, this would only work around the problem and it'd be interesting to find the cause. Can you somehow give instructions on how to reproduce that bug?

**Comment by ThoreKr** [comment]
I'm seeing similar issues (after upgrading from 1.17.x). I've then started to go through individual releases until it crashes severely in 1.21.0.while trying to recreate aliases, summaries and heartbeats.

```
2021-04-20T13:26:16.121560512+02:00 [INFO ] potentially running migration 'rename language mappings table'
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:32
[0.027ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="custom_rules"
2021-04-20T13:26:16.121690795+02:00 [INFO ] potentially running migration 'add cascade constraints'
2021-04-20T13:26:16.121698558+02:00 [INFO ] not attempting to drop and regenerate constraints on sqlite
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:32
[0.018ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="users"
2021/04/20 13:26:16 /home/thore/Projects/wakapi/config/config.go:120
[0.025ms] [rows:-] SELECT * FROM `users` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:32
[0.016ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="key_string_values"
2021/04/20 13:26:16 /home/thore/Projects/wakapi/config/config.go:121
[0.014ms] [rows:-] SELECT * FROM `key_string_values` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:32
[0.016ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="users"
2021/04/20 13:26:16 /home/thore/Projects/wakapi/config/config.go:122
[0.025ms] [rows:-] SELECT * FROM `users` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:32
[0.018ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="aliases"
2021/04/20 13:26:16 /home/thore/Projects/wakapi/config/config.go:122
[0.014ms] [rows:-] SELECT * FROM `aliases` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:20
[0.076ms] [rows:1] PRAGMA foreign_keys
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:83
[0.017ms] [rows:-] SELECT sql FROM sqlite_master WHERE type = "table" AND tbl_name = "aliases" AND name = "aliases"
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:95
[0.015ms] [rows:-] SELECT * FROM `aliases` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:108 table aliases already exists
[0.009ms] [rows:0] CREATE TABLE aliases
(
    id      integer primary key autoincrement,
   `type` integer NOT NULL,
    user_id varchar(255) not null,
    key     varchar(255) not null,
    value   varchar(255) not null
)
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:32
[0.018ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="users"
2021/04/20 13:26:16 /home/thore/Projects/wakapi/config/config.go:123
[0.021ms] [rows:-] SELECT * FROM `users` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:32
[0.015ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="heartbeats"
2021/04/20 13:26:16 /home/thore/Projects/wakapi/config/config.go:123
[0.017ms] [rows:-] SELECT * FROM `heartbeats` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:20
[0.014ms] [rows:1] PRAGMA foreign_keys
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:83
[0.017ms] [rows:-] SELECT sql FROM sqlite_master WHERE type = "table" AND tbl_name = "heartbeats" AND name = "heartbeats"
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:95
[0.017ms] [rows:-] SELECT * FROM `heartbeats` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:108 table heartbeats already exists
[0.006ms] [rows:0] CREATE TABLE heartbeats
(
    id               integer primary key autoincrement,
   `user_id` text NOT NULL,
    entity           varchar(255) not null,
    type             varchar(255),
    category         varchar(255),
    project          varchar(255),
    branch           varchar(255),
    language         varchar(255),
    is_write         bool,
    editor           varchar(255),
    operating_system varchar(255),
    time             timestamp default CURRENT_TIMESTAMP
, `machine` varchar(255))
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:32
[0.019ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="users"
2021/04/20 13:26:16 /home/thore/Projects/wakapi/config/config.go:124
[0.021ms] [rows:-] SELECT * FROM `users` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:32
[0.015ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="summaries"
2021/04/20 13:26:16 /home/thore/Projects/wakapi/config/config.go:124
[0.014ms] [rows:-] SELECT * FROM `summaries` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:20
[0.014ms] [rows:1] PRAGMA foreign_keys
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:83
[0.016ms] [rows:-] SELECT sql FROM sqlite_master WHERE type = "table" AND tbl_name = "summaries" AND name = "summaries"
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:95
[0.015ms] [rows:-] SELECT * FROM `summaries` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:108 table summaries already exists
[0.007ms] [rows:0] CREATE TABLE summaries
(
    id        integer primary key autoincrement,
   `user_id` text NOT NULL,
    from_time timestamp default CURRENT_TIMESTAMP not null,
    to_time   timestamp default CURRENT_TIMESTAMP not null
)
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:32
[0.018ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="users"
2021/04/20 13:26:16 /home/thore/Projects/wakapi/config/config.go:125
[0.019ms] [rows:-] SELECT * FROM `users` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:32
[0.013ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="summaries"
2021/04/20 13:26:16 /home/thore/Projects/wakapi/config/config.go:125
[0.013ms] [rows:-] SELECT * FROM `summaries` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:20
[0.013ms] [rows:1] PRAGMA foreign_keys
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:83
[0.014ms] [rows:-] SELECT sql FROM sqlite_master WHERE type = "table" AND tbl_name = "summaries" AND name = "summaries"
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:95
[0.016ms] [rows:-] SELECT * FROM `summaries` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:108 table summaries already exists
[0.006ms] [rows:0] CREATE TABLE summaries
(
    id        integer primary key autoincrement,
   `user_id` text NOT NULL,
    from_time timestamp default CURRENT_TIMESTAMP not null,
    to_time   timestamp default CURRENT_TIMESTAMP not null
)
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:32
[0.019ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="users"
2021/04/20 13:26:16 /home/thore/Projects/wakapi/config/config.go:126
[0.019ms] [rows:-] SELECT * FROM `users` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:32
[0.014ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="language_mappings"
2021/04/20 13:26:16 /home/thore/Projects/wakapi/config/config.go:126
[0.015ms] [rows:-] SELECT * FROM `language_mappings` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:20
[0.013ms] [rows:1] PRAGMA foreign_keys
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:83
[0.014ms] [rows:-] SELECT sql FROM sqlite_master WHERE type = "table" AND tbl_name = "language_mappings" AND name = "language_mappings"
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:95
[0.014ms] [rows:-] SELECT * FROM `language_mappings` LIMIT 1
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:108
[0.175ms] [rows:0] CREATE TABLE `language_mappings__temp` (`id` integer,`user_id` text NOT NULL,`extension` varchar(16),`language` varchar(64),PRIMARY KEY (`id`),CONSTRAINT `fk_language_mappings_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE)
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:108
[0.026ms] [rows:0] INSERT INTO `language_mappings__temp`(`id`,`user_id`,`extension`,`language`) SELECT `id`,`user_id`,`extension`,`language` FROM `language_mappings`
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:108
[0.067ms] [rows:0] DROP TABLE `language_mappings`
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:108
[0.573ms] [rows:0] ALTER TABLE `language_mappings__temp` RENAME TO `language_mappings`
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:188
[0.028ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "table" AND tbl_name = "language_mappings" AND (sql LIKE "%CONSTRAINT \"fk_language_mappings_user\" %" OR sql LIKE "%CONSTRAINT fk_language_mappings_user %" OR sql LIKE "%CONSTRAINT `fk_language_mappings_user`%")
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:259
[0.017ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "language_mappings" AND name = "idx_language_mapping_composite"
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:242
[1.581ms] [rows:0] CREATE UNIQUE INDEX `idx_language_mapping_composite` ON `language_mappings`(`user_id`,`extension`)
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:259
[0.027ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type = "index" AND tbl_name = "language_mappings" AND name = "idx_language_mapping_user"
2021/04/20 13:26:16 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:242
[1.319ms] [rows:0] CREATE INDEX `idx_language_mapping_user` ON `language_mappings`(`user_id`)
```
So the best way around this is to migrate the backup db to postgres and start the migrations from there?

**Comment by ThoreKr** [comment]
> Btw., would you be willing to migrate from SQLite to MySQL if a smooth migration script was provided or you using SQLite intentionally, e.g. because of hardware constraints or so?

Maybe to throw in a second opinion: I'm using sqlite because I run wakapi on my laptop alongside the editors I want to track and that just simple and easy. I do have a postgres instance running all the time, so that would be my second choice.

Migration wise, I briefly tested pgloader but it was unhappy about the booleans stored as numerics.
I'll probably will just pipe it through python and see how it goes.

**Comment by muety** [comment]
Thanks for your feedback @ThoreKr! 

Regarding the migration, I wrote [sqlite2mysql.go](https://github.com/muety/wakapi/blob/master/scripts/sqlite2mysql.go) in the meanwhile, but it's not very well tested, yet.

**Comment by muety** [comment]
> So the best way around this is to migrate the backup db to postgres and start the migrations from there?

I'll take a look at your specific issue later and let you know how to best solve it.

**Comment by muety** [comment]
@ThoreKr Did you get an error message? I might just have overlooked it, but I can't see an actual error the logs you posted.

**Comment by ThoreKr** [comment]
@muety not directly, 1.21.0 still starts, but in that release these unapplied changes start to show up, which ultimately lead to the same error and panic out as posted by YC.

**Comment by muety** [comment]
@ThoreKr Try to set `db.automgirate_fail_silently` in your config (or `WAKAPI_DB_AUTOMIGRATE_FAIL_SILENTLY` as an env var) to `true` and see if it starts. I believe the changes that fail to be applied with SQLite are not crucial, but mostly only constraints, indexes, etc. – nothing that would stop Wakapi from working. However, migrating to MySQL or Postgres in the future would still the preferable way as there will likely be less problems to come.

**Comment by ThoreKr** [comment]
@muety first of all thank you for caring so much.

Unfortunately automigrate_fail_silently didn't help on 1.26.5

```
[0.081ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="aliases"
2021/04/22 01:14:53 /home/thore/Projects/wakapi/config/config.go:185
[0.087ms] [rows:-] SELECT * FROM `aliases` LIMIT 1
2021/04/22 01:14:53 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:20
[0.144ms] [rows:1] PRAGMA foreign_keys
2021/04/22 01:14:53 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:83
[0.092ms] [rows:-] SELECT sql FROM sqlite_master WHERE type = "table" AND tbl_name = "aliases" AND name = "aliases"
2021/04/22 01:14:53 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:95
[0.089ms] [rows:-] SELECT * FROM `aliases` LIMIT 1
2021/04/22 01:14:53 /home/thore/go/pkg/mod/gorm.io/driver/sqlite@v1.1.3/migrator.go:108 table aliases already exists
[0.044ms] [rows:0] CREATE TABLE aliases
(
    id      integer primary key autoincrement,
    type    integer      not null,
    user_id varchar(255) not null,
    key     varchar(255) not null,
    value   varchar(255) not null
)
2021-04-22T01:14:53.738423845+02:00 [ERROR] table aliases already exists
panic: table aliases already exists

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc00000e0d8, 0xc000258780, 0x1c, 0x0, 0x0, 0x0)
	/home/thore/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/standard_formatter.go:57 +0xc5
github.com/emvi/logbuch.(*Logger).Fatal(0xc000154180, 0xc000258780, 0x1c, 0x0, 0x0, 0x0)
	/home/thore/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/logger.go:132 +0xb3
github.com/emvi/logbuch.Fatal(...)
	/home/thore/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/funcs.go:55
github.com/muety/wakapi/migrations.RunSchemaMigrations(0xc000243a70, 0xc000023b00)
	/home/thore/Projects/wakapi/migrations/migrations.go:39 +0x9e
github.com/muety/wakapi/migrations.Run(0xc000243a70, 0xc000023b00)
	/home/thore/Projects/wakapi/migrations/migrations.go:33 +0x4d
main.main()
	/home/thore/Projects/wakapi/main.go:131 +0x389
````

Not entirely sure what is going on here, so I shifted my efforts to just migrate the database, as this seems to be the better long-term solution anyways.

First of, the migration script almost worked, I had to tweak a few things, should I document them somewhere?

One of the issues was that the hash column didn't exist in the sqlite database and I wrote a small data migration, to compute it on the go. After a bit of massaging the database it seems like heartbeats are correctly stored again.

**Comment by muety** [comment]
> Unfortunately automigrate_fail_silently didn't help on 1.26.5

It's not yet in any of the releases, but currently only on `master`. I'll add a few other things soon and then publish a new release. If you compile from source, failing silently should be working.

> I had to tweak a few things, should I document them somewhere?

That'd be awesome! Feel free to directly apply those changes to the script and do a PR. If those tweaks can't be reflected in code, please document them in the "Usage" comment within that same script.
