### ISSUE TITLE
Data not send to Api - Failed to send heartbeat

### ISSUE THREAD

**Issue by Developer66** [muety/wakapi#214]
Hey,
thanks to the great work. I am using the Windows version. Starting and setting up worked very well.
Also migrating the data from Wakatime to Wakapi.

My problem is, that there are no data send to the API. The Log has a fatal error in sending hearthbeats. Datas also wont be send to Wakatime
```
{
   "caller":"/home/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/heartbeat/heartbeat.go:47",
   "func":"Run",
   "level":"fatal",
   "message":"failed to send heartbeat(s): failed to load command parameters: failed to retrieve entity",
   "now":"2021-06-24T14:11:01+02:00",
   "version":""
}
```

The API and APP health is both 1.

My .wakatime.cfg looks like this:
```
[settings]
api_url = http://localhost:3000/api
api_key = 8e5756d6-f609-426e-9a24-85ae59b7c149
```

Thanks for your help.
Developer66

**Comment by muety** [comment]
Hi @Developer66!

The error is thrown in [this part](https://github.com/wakatime/wakatime-cli/blob/c2076c0e1abc1449baf5b7ac7db391b06041c719/cmd/legacy/heartbeat/params.go#L187) of _wakatime-cli_, far before any API call will happen. I would assume that your setup is correct and this is an issue with either the CLI or the editor plugin. Which editor are you working with? 

I would suggest to file this issue at https://github.com/wakatime/wakatime-cli, as it's most likely not specific to Wakapi.

Thanks for your feedback and good luck getting this fixed!

**Comment by Developer66** [comment]
Hey,
working with the Wakatime server works well and there is no error... Even with my account on https://wakapi.dev/
it is not working. Same error.

I tried Rider, IntelliJ, PHPStorm and Datagrip and commiting va CLI for tracking the coding activity. 
Nothing worked.

I tried now different wakatime cli version... also nothing worked. Also disabled my firewall, no effect.

**Comment by muety** [comment]
I might have found the issue and it may be fixed with the latest version. Please try release 1.29.1 and report if the problem is still there.

**Comment by Developer66** [comment]
Works fine for me now.
Thanks

**Comment by muety** [comment]
Setting your `api_url` to `/api/heartbeart` will probably work. However, I don't know why this problem even occurs in the first place, as the CLI should, in theory, construct there URL like this: https://github.com/wakatime/wakatime-cli/blob/c2076c0e1abc1449baf5b7ac7db391b06041c719/pkg/api/heartbeat.go#L24.

**Comment by Developer66** [comment]
Does also not work... No Data displayed.

My .wakatime.cfg
```
[settings]
api_url = http://localhost:3000/api/heartbeart
api_key = af317d3c-f776-4eae-a0bb-8014b0f1994e
```

**Comment by muety** [comment]
What are the logs then?

**Comment by Developer66** [comment]
The log is empty... Even when i execute a heartbeat by cli... no log written

**Comment by muety** [comment]
Please set the API URL to this, temporarily: https://bin.muetsch.io/wakapi-214

(You can inspect the request afterwards at https://bin.muetsch.io/web/wakapi-214?token=jIpl9g5UHSud-0IxPVWiX1baDz1iQJ3h_MUCT6FTuStn)

**Comment by Developer66** [comment]
This looks pretty good in my eyes... no idea why nothing is displayed in the local instance

**Comment by Developer66** [comment]
Anything new?

**Comment by Developer66** [comment]
Damm,
I tried now different settings.
Installed the Wakapi on a fresh Win10 and Ubuntu 20.04... both are not working. I installed the wakatime plugin over the jetbrain ide and it has the version 13.0.2. So my os, some settings or firewall is not the problem. The wakatime log is always empty.

I also installed a request basket server and the request are correct with the right infos.
I installed Hakatime using docker... this is working perfectly. Time is directly tracked.

The request in the cli log looks everytime like this:
`2021-06-28T15:11:37.6956335+02:00 [INFO ] [request] status=404, method=POST, uri=/api/heartbeart, duration=0s, bytes=19, addr=127.0.0.1:49283, user=-`
I think the status means 404 not found... so there must be some error there... also 19 bytes is a little bit to low i think. Is is possible to print out what is send to the api. Hope this are some more details to debug the error.

In the wakatime.cfg i tried also different settings:
```
[settings]
api_url = http://localhost:3000/api/heartbeart
api_key = af317d3c-f776-4eae-a0bb-8014b0f1994e
```
```
[settings]
api_url = http://localhost:3000/api
api_key = af317d3c-f776-4eae-a0bb-8014b0f1994e
```
Both not working. Also setting the Server to different ports

**Comment by muety** [comment]
I think `/api/heartbeart` is the correct API to use with current WakaTime CLI version.

Also, please try to set `env: development` in your config and see if some useful debug logs are printed in addition to the above request log.

**Comment by muety** [comment]
Also, what happens if you run the CLI manually, like `./wakatime-cli --entity ./wakatime-cli`

**Comment by Developer66** [comment]
> 
> 
> Also, what happens if you run the CLI manually, like `./wakatime-cli --entity ./wakatime-cli`?
There is an new log in the wakapi cli with status 404 and 19 bytes sent but no log is written in the logfile about some failure.


> 
> 
> I think `/api/heartbeart` is the correct API to use with current WakaTime CLI version.
> 
> Also, please try to set `env: development` in your config and see if some useful debug logs are printed in addition to the above request log.
Cant start in develop mode :( 
```
2021-06-28T20:11:22.9517548+02:00 [ERROR] unexpected end of JSON input
panic: unexpected end of JSON input

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc0000040d8, 0xc26525, 0x1c, 0x0, 0x0, 0x0)
        C:/Users/runneradmin/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:57 +0xc9
github.com/emvi/logbuch.(*Logger).Fatal(0xc00014c000, 0xc26525, 0x1c, 0x0, 0x0, 0x0)
        C:/Users/runneradmin/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0xba
github.com/emvi/logbuch.Fatal(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
github.com/muety/wakapi/config.readColors(0xc15708)
        D:/a/wakapi/wakapi/config/config.go:264 +0x167
github.com/muety/wakapi/config.Load(0xc15708, 0x8, 0x8)
        D:/a/wakapi/wakapi/config/config.go:332 +0x27c
main.main()
        D:/a/wakapi/wakapi/main.go:95 +0x70
```

**Comment by Developer66** [comment]
I build it now and was able to set the env to development... 

I think there is no important info in the log... :(

[serverLog.txt](https://github.com/muety/wakapi/files/6728662/serverLog.txt)

**Comment by muety** [comment]
Here's you problem: you wrote "heartbeart" instead of "heartbeat".

**Comment by Developer66** [comment]
A shit... Now it works when i send the Data using the cli
`wakatime-cli.exe --entity wakatime-cli.exe`
Log looks like this:
`2021-06-28T21:13:25.2071431+02:00 [INFO ] [request] status=201, method=POST, uri=/api/heartbeat, duration=73.0187ms, bytes=291, addr=127.0.0.1:63309, user=Developer66`

But using the IDE generates following log with status 401 Unauthorized
`2021-06-28T21:15:09.7142319+02:00 [INFO ] [request] status=401, method=POST, uri=/api/heartbeat, duration=515.1µs, bytes=16, addr=127.0.0.1:63344, user=-`

**Comment by muety** [comment]
You will probably have to set the API key inside your IDE plugin's settings in addition to the config file. Think the IntelliJ plugin works like that.

**Comment by Mte90** [comment]
I am facing errors with kate-wakatime and vim-wakatime that are similar.
```
wakatime: Status code: 201
wakatime: URL: "https://wakapi.dev/api/v1/users/current/heartbeats.bulk"
wakatime: Sent data successfully
wakatime: Status code: 400
wakatime: URL: "https://wakapi.dev/api/v1/users/current/heartbeats.bulk"
wakatime: URL: "https://wakapi.dev/api/v1/users/current/heartbeats.bulk"
wakatime: Request did not succeed, status code: 400
```
Few days ago was working for me.

**Comment by muety** [comment]
That's weird. Can you please do me a favor and temporarily set your API URL to `https://bin.muetsch.io/wakapi-100 `? This way, we can investigate the requests' payload at https://bin.muetsch.io/web/wakapi-100?token=UE5LvZ9NgHwhE90kTW0tXMyxWWONIU7yKMEfTJGQbSdV.

**Comment by Mte90** [comment]
```
wakatime: Status code: 405
wakatime: URL: "https://bin.muetsch.io/web/wakapi-100?token=UE5LvZ9NgHwhE90kTW0tXMyxWWONIU7yKMEfTJGQbSdV/v1/users/current/heartbeats.bulk"
wakatime: URL: "https://bin.muetsch.io/web/wakapi-100?token=UE5LvZ9NgHwhE90kTW0tXMyxWWONIU7yKMEfTJGQbSdV/v1/users/current/heartbeats.bulk"
wakatime: Request did not succeed, status code: 405
wakatime: Status code: 405
wakatime: URL: "https://bin.muetsch.io/web/wakapi-100?token=UE5LvZ9NgHwhE90kTW0tXMyxWWONIU7yKMEfTJGQbSdV/v1/users/current/heartbeats.bulk"
wakatime: URL: "https://bin.muetsch.io/web/wakapi-100?token=UE5LvZ9NgHwhE90kTW0tXMyxWWONIU7yKMEfTJGQbSdV/v1/users/current/heartbeats.bulk"
wakatime: Request did not succeed, status code: 405
```

**Comment by muety** [comment]
Please read my comment again, the API URL is supposed to be https://bin.muetsch.io/wakapi-100, not https://bin.muetsch.io/web/wakapi-100?token=UE5LvZ9NgHwhE90kTW0tXMyxWWONIU7yKMEfTJGQbSdV.

**Comment by Mte90** [comment]
Ok just to be sure I configured in that way:

```
[settings]
api_key=[my wakapi key]
#api_url=https://wakapi.dev/api
api_url=https://bin.muetsch.io/web/wakapi-100
exclude=Desktop, vendor
hide_file_names=true
hidefilenames=true
```

```
wakatime: Status code: 404
wakatime: URL: "https://bin.muetsch.io/web/wakapi-100/v1/users/current/heartbeats.bulk"
wakatime: URL: "https://bin.muetsch.io/web/wakapi-100/v1/users/current/heartbeats.bulk"
wakatime: Request did not succeed, status code: 404
wakatime: Status code: 404
wakatime: URL: "https://bin.muetsch.io/web/wakapi-100/v1/users/current/heartbeats.bulk"
wakatime: URL: "https://bin.muetsch.io/web/wakapi-100/v1/users/current/heartbeats.bulk"
wakatime: Request did not succeed, status code: 404
```

I tried in Kate and Neovim with those settings so something should be tracked.

**Comment by muety** [comment]
It is `https://bin.muetsch.io/wakapi-100` NOT `https://bin.muetsch.io/web/wakapi-100`.

**Comment by Mte90** [comment]
Ok request now sent.
Sorry this is happens when I am busy in too many things -.-'

**Comment by muety** [comment]
Alright, I just investigated your requests. Here's the problem. Look at this JSON document:

```json
[
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838929,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "is_write": true,
      "language": "Python",
      "project": "2021",
      "time": 1625838929,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838950,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838951,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838952,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838953,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "is_write": true,
      "language": "Python",
      "project": "2021",
      "time": 1625838953,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838967,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838968,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838974,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838977,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838983,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838986,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838987,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838988,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838989,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838990,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838991,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838992,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838994,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838995,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838996,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625838998,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625839003,
      "type": "file"
    }
  ],
  [
    {
      "category": "coding",
      "entity": "HIDDEN.py",
      "language": "Python",
      "project": "2021",
      "time": 1625839004,
      "type": "file"
    }
  ]
]
```

What your plugins sends is an array of arrays of heartbeats. The correct way would be to have an array of heartbeats instead, i.e. no nested arrays.

**Wanted:** `[ { ... } ]`
**Actual (currently): `[[ { ... } ]]`

This is a bug with your plugin. Please report it at their repository.

**Comment by muety** [comment]
What does wakatime log file say? What HTTP status is returned?

**Comment by Mte90** [comment]
So on vim I did a new bucket to avoid any confusion as seems that the previous is used by someone.

https://bin.muetsch.io/web/wakapi-101?token=NNWZBE6RKa2whIL5mKa_MX7pgSRTHtpD0u5O0fvNaa2J

The error from the official vim plugin is 102

**Comment by muety** [comment]
It looks like for the Vim plugin you might have to set the API URL to `/api`. Also, please try to enable the plugin's debug mode as described [here](https://github.com/wakatime/vim-wakatime#troubleshooting). Maybe the log will tell something useful.

**Comment by Mte90** [comment]
```
{"now": "2021/07/19 19:03:37 +0200", "version": "13.0.5", "plugin": "vim/800 vim-wakatime/8.0.0", "time": 1626714177.0, "caller": "/home/mte90/.vim/plugged/vim-wakatime/packages/wakatime/api.py", "lineno": 55, "file": "/home/www/VVV/www/settings.php", "level": "DEBUG", "message": "Sending heartbeats to api at https://wakapi.dev/api/"}
{"now": "2021/07/19 19:03:37 +0200", "version": "13.0.5", "plugin": "vim/800 vim-wakatime/8.0.0", "time": 1626714177.0, "caller": "/home/mte90/.vim/plugged/vim-wakatime/packages/wakatime/api.py", "lineno": 61, "file": "/home/www/VVV/www/settings.php", "level": "DEBUG", "message": "[{'time': 1626714177.0, 'entity': 'HIDDEN.php', 'type': 'file', 'category': None, 'is_write': False, 'project': 'www', 'branch': None, 'language': 'PHP', 'dependencies': None, 'lines': None, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.0.5 (Linux-5.12.17-1-siduction-amd64-x86_64-with-glibc2.31) Python3.9.2.final.0 vim/800 vim-wakatime/8.0.0'}]"}
{"now": "2021/07/19 19:03:37 +0200", "version": "13.0.5", "plugin": "vim/800 vim-wakatime/8.0.0", "time": 1626714177.0, "caller": "/home/mte90/.vim/plugged/vim-wakatime/packages/wakatime/api.py", "lineno": 154, "file": "/home/www/VVV/www/settings.php", "level": "DEBUG", "message": "{'response_code': 404, 'response_text': '404 page not found\\n'}"}
{"now": "2021/07/19 19:03:37 +0200", "version": "13.0.5", "plugin": "vim/800 vim-wakatime/8.0.0", "time": 1626714177.0, "caller": "/home/mte90/.vim/plugged/vim-wakatime/packages/wakatime/api.py", "lineno": 325, "file": "/home/www/VVV/www/settings.php", "level": "WARNING", "message": "{'response_code': 404, 'response_content': '404 page not found\\n'}"}
```

I added the final slash but I get the 102 error as always.

**Comment by muety** [comment]
Put `api_url = https://wakapi.dev/api`

**Comment by Mte90** [comment]
I discovered the issue as the vim plugin doesn't write the url used for the requests.
Seems that the vim plugin look in the config file for the whole domain to the heartbeat api and not just the domain.

I am investigating on that :-)

Thanks for the help
