### ISSUE TITLE
Problem with SQLite and DisableForeignKeyConstraintWhenMigrating

### ISSUE THREAD

**Issue by mawoka-myblock** [muety/wakapi#280]
**Describe the bug**
It just crashes in startup with the following error:
```
2021-12-14T14:57:47.554225435Z [WARN ] with sqlite, only a single connection is supported
2021-12-14T14:57:47.555654665Z [INFO ] potentially running migration '20201103-rename_language_mappings_table'
2021-12-14T14:57:47.555704689Z [INFO ] potentially running migration '20201106-migration_cascade_constraints'
2021-12-14T14:57:47.555714868Z [INFO ] not attempting to drop and regenerate constraints on sqlite
2021-12-14T14:57:47.555717223Z [INFO ] potentially running migration '20210202-fix_cascade_for_alias_user_constraint'
2021-12-14T14:57:48.098528901Z [ERROR] constraints not implemented on sqlite, consider using DisableForeignKeyConstraintWhenMigrating, more details https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft#all-new-migrator
2021-12-14T14:57:47.555720659Z [INFO ] not attempting to drop and regenerate constraints on sqlite
panic: constraints not implemented on sqlite, consider using DisableForeignKeyConstraintWhenMigrating, more details https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft#all-new-migrator
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc00000e030, 0xd3f166, 0xbd, 0x0, 0x0, 0x0)
goroutine 1 [running]:
github.com/emvi/logbuch.(*Logger).Fatal(0xc000112000, 0xd3f166, 0xbd, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:57 +0xc5
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0xb3
github.com/emvi/logbuch.Fatal(...)
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
	/src/migrations/migrations.go:39 +0x9e
github.com/muety/wakapi/migrations.RunSchemaMigrations(0xc00029e000, 0xc00023c000)
github.com/muety/wakapi/migrations.Run(0xc00029e000, 0xc00023c000)
	/src/migrations/migrations.go:33 +0x4d
	/src/main.go:142 +0x3dd
main.main()
```

**System information**
Please provide information on:
* Latest docker image
* Database: SQLite

**Comment by muety** [comment]
I assume you just tried to upgrade to the latest version? Which version were you using previously?

**Comment by muety** [comment]
As a workaround, please try to set `WAKAPI_DB_AUTOMIGRATE_FAIL_SILENTLY` to `true`.

**Comment by YC** [comment]
Also experiencing issue with SQLite
```
2021-12-15T07:23:03.850677323Z [WARN ] with sqlite, only a single connection is supported
2021-12-15T07:23:03.87565514Z [INFO ] potentially running migration '20201103-rename_language_mappings_table'
2021-12-15T07:23:03.875884861Z [INFO ] potentially running migration '20201106-migration_cascade_constraints'
2021-12-15T07:23:03.875896861Z [INFO ] not attempting to drop and regenerate constraints on sqlite
2021-12-15T07:23:03.875899021Z [INFO ] potentially running migration '20210202-fix_cascade_for_alias_user_constraint'
2021-12-15T07:23:03.875901421Z [INFO ] not attempting to drop and regenerate constraints on sqlite
2021-12-15T07:23:05.546254455Z [ERROR] constraints not implemented on sqlite, consider using DisableForeignKeyConstraintWhenMigrating, more details https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft#all-new-migrator
panic: constraints not implemented on sqlite, consider using DisableForeignKeyConstraintWhenMigrating, more details https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft#all-new-migrator

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0x400000e030, 0xc23fc5, 0xbd, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:57 +0xa4
github.com/emvi/logbuch.(*Logger).Fatal(0x4000098000, 0xc23fc5, 0xbd, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x98
github.com/emvi/logbuch.Fatal(...)
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
github.com/muety/wakapi/migrations.RunSchemaMigrations(0x400021e000, 0x40001ba000)
	/src/migrations/migrations.go:39 +0x8c
github.com/muety/wakapi/migrations.Run(0x400021e000, 0x40001ba000)
	/src/migrations/migrations.go:33 +0x44
main.main()
	/src/main.go:142 +0x398
```

```
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> SELECT * FROM sqlite_master;
table|users|users|2|CREATE TABLE `users` (`id` text,`api_key` text UNIQUE,`email` text,`password` text,`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,`last_logged_in_at` timestamp DEFAULT CURRENT_TIMESTAMP,`share_data_max_days` integer DEFAULT 0,`share_editors` numeric DEFAULT false,`share_languages` numeric DEFAULT false,`share_projects` numeric DEFAULT false,`share_oss` numeric DEFAULT false,`share_machines` numeric DEFAULT false,`is_admin` numeric DEFAULT false,`has_data` numeric DEFAULT false,`wakatime_api_key` text,`reset_token` text, `reports_weekly` numeric DEFAULT false, `location` text, `share_labels` numeric DEFAULT false,PRIMARY KEY (`id`))
index|sqlite_autoindex_users_1|users|3|
index|sqlite_autoindex_users_2|users|4|
index|idx_user_email|users|5|CREATE UNIQUE INDEX `idx_user_email` ON `users`(`email`)
table|key_string_values|key_string_values|6|CREATE TABLE `key_string_values` (`key` text,`value` text,PRIMARY KEY (`key`))
index|sqlite_autoindex_key_string_values_1|key_string_values|7|
table|summary_items|summary_items|9304|CREATE TABLE `summary_items` (`id` integer,`summary_id` integer,`type` integer,`key` text,`total` integer,PRIMARY KEY (`id`),CONSTRAINT `fk_summaries_operating_systems` FOREIGN KEY (`summary_id`) REFERENCES `summaries`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `fk_summaries_machines` FOREIGN KEY (`summary_id`) REFERENCES `summaries`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `fk_summary_items_summary` FOREIGN KEY (`summary_id`) REFERENCES `summaries`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `fk_summaries_projects` FOREIGN KEY (`summary_id`) REFERENCES `summaries`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `fk_summaries_languages` FOREIGN KEY (`summary_id`) REFERENCES `summaries`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `fk_summaries_editors` FOREIGN KEY (`summary_id`) REFERENCES `summaries`(`id`) ON DELETE CASCADE ON UPDATE CASCADE)
index|idx_type|summary_items|9311|CREATE INDEX `idx_type` ON `summary_items`(`type`)
table|diagnostics|diagnostics|17257|CREATE TABLE "diagnostics" (`id` integer,`user_id` text NOT NULL,`platform` text,`architecture` text,`plugin` text,`cli_version` text,`logs` text,`stack_trace` text,PRIMARY KEY (`id`))
index|idx_diagnostics_user|diagnostics|4684|CREATE INDEX `idx_diagnostics_user` ON `diagnostics`(`user_id`)
table|aliases|aliases|8|CREATE TABLE "aliases" (`id` integer,`type` integer NOT NULL,`user_id` text NOT NULL,`key` text NOT NULL,`value` text NOT NULL,PRIMARY KEY (`id`),CONSTRAINT `fk_aliases_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE)
index|idx_alias_type_key|aliases|9|CREATE INDEX `idx_alias_type_key` ON `aliases`(`type`,`key`)
index|idx_alias_user|aliases|12|CREATE INDEX `idx_alias_user` ON `aliases`(`user_id`)
table|heartbeats|heartbeats|10|CREATE TABLE "heartbeats" (`id` integer,`user_id` text NOT NULL,`entity` text NOT NULL,`type` text,`category` text,`project` text,`branch` text,`language` text,`is_write` numeric,`editor` text,`operating_system` text,`machine` text,`time` timestamp,`hash` varchar(17),`origin` text,`origin_id` text,`created_at` timestamp, `user_agent` text,PRIMARY KEY (`id`),CONSTRAINT `fk_heartbeats_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE)
index|idx_time_user|heartbeats|5198|CREATE INDEX `idx_time_user` ON `heartbeats`(`user_id`)
index|idx_entity|heartbeats|10705|CREATE INDEX `idx_entity` ON `heartbeats`(`entity`)
index|idx_language|heartbeats|4737|CREATE INDEX `idx_language` ON `heartbeats`(`language`)
index|idx_time|heartbeats|15310|CREATE INDEX `idx_time` ON `heartbeats`(`time`)
index|idx_heartbeats_hash|heartbeats|3925|CREATE UNIQUE INDEX `idx_heartbeats_hash` ON `heartbeats`(`hash`)
table|summaries|summaries|1612|CREATE TABLE "summaries" (`id` integer,`user_id` text NOT NULL,`from_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`to_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`),CONSTRAINT `fk_summaries_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE)
index|idx_time_summary_user|summaries|1504|CREATE INDEX `idx_time_summary_user` ON `summaries`(`user_id`,`from_time`,`to_time`)
table|language_mappings|language_mappings|18930|CREATE TABLE "language_mappings" (`id` integer,`user_id` text NOT NULL,`extension` varchar(16),`language` varchar(64),PRIMARY KEY (`id`),CONSTRAINT `fk_language_mappings_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE)
index|idx_language_mapping_user|language_mappings|21|CREATE INDEX `idx_language_mapping_user` ON `language_mappings`(`user_id`)
index|idx_language_mapping_composite|language_mappings|24|CREATE UNIQUE INDEX `idx_language_mapping_composite` ON `language_mappings`(`user_id`,`extension`)
table|project_labels|project_labels|20455|CREATE TABLE "project_labels" (`id` integer,`user_id` text NOT NULL,`project_key` text,`label` varchar(64),PRIMARY KEY (`id`))
```

**Comment by muety** [comment]
@YC Could you please send me the SQLite database for debugging? If it contains private data, feel free to empty the respective tables first.

**Comment by YC** [comment]
[wakapi.db.zip](https://github.com/muety/wakapi/files/7718370/wakapi.db.zip)
credentials: yc:aaaaaa

**Comment by muety** [comment]
Turns out GORM has implemented constraints for SQLite in the meanwhile (see https://github.com/go-gorm/sqlite/pull/55). An upgrade should probably fix the issue. Stay tuned.
