### ISSUE TITLE
Docker Container Stop And Error IS "panic: reflect: Call using zero Value argument"

### ISSUE THREAD

**Issue by Wanxp** [muety/wakapi#299]
**Describe the bug**
I run wakapi server in docker. and it run very well, it can receive data and visited by me on 127.0.0.1:3000. but it always stoped after a period of time. But I donot know why. here is a details

**System information**
Please provide information on:
* Wakapi version : v1.17.2 @ sqlite3
* Operating system
    * Linux: Ubuntu 18.04
    * Docker:  Docker version 20.10.2, build 2291f61
* Database :SQLite
* Docker Image : 
```shell
REPOSITORY                  TAG        IMAGE ID       CREATED         SIZE
n1try/wakapi                latest     8cda09755423   13 months ago   136MB
```
* Docker Run Commd:
```shell
docker run -d   -p 3000:3000   -e "WAKAPI_PASSWORD_SALT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1)"   -v wakapi-data:/data   --name wakapi n1try/wakapi
```
full stack like this, from start to error stoped
```text
Starting Application
2022/01/04 00:53:31 potentially running migration 'rename language mappings table'
2022/01/04 00:53:31 potentially running migration 'add cascade constraints'
2022/01/04 00:53:31 not attempting to drop and regenerate constraints on sqlite
2022/01/04 00:53:32 potentially running migration 'apply fixtures'
2022/01/04 00:53:32 applied 0 fixtures
2022/01/04 00:53:32 Generating summaries.
2022/01/04 00:53:32 Listening on 0.0.0.0:3000
2022/01/04 00:53:32 Successfully generated summary (2021-12-31 00:00:00 +0000 UTC, 2022-01-01 00:00:00 +0000 UTC, 97***2@qq.com).
2022/01/04 00:53:32 Successfully generated summary (2022-01-01 00:00:00 +0000 UTC, 2022-01-02 00:00:00 +0000 UTC, 97***2@qq.com).
2022/01/04 00:53:32 Successfully generated summary (2022-01-02 00:00:00 +0000 UTC, 2022-01-03 00:00:00 +0000 UTC, 97***2@qq.com).
2022/01/04 00:53:32 Successfully generated summary (2022-01-03 00:00:00 +0000 UTC, 2022-01-04 00:00:00 +0000 UTC, 97***2@qq.com).
172.17.0.1 - - [04/Jan/2022:00:53:36 +0000] "GET / HTTP/1.0" 200 5330
172.17.0.1 - - [04/Jan/2022:00:54:13 +0000] "POST /api/heartbeat HTTP/1.0" 201 27
172.17.0.1 - - [04/Jan/2022:00:54:14 +0000] "POST /api/heartbeat HTTP/1.0" 201 203
172.17.0.1 - - [04/Jan/2022:00:55:41 +0000] "POST /api/heartbeat HTTP/1.0" 201 27
172.17.0.1 - - [04/Jan/2022:00:56:07 +0000] "POST /api/heartbeat HTTP/1.0" 201 27
172.17.0.1 - - [04/Jan/2022:00:56:51 +0000] "POST /api/heartbeat HTTP/1.0" 201 27
172.17.0.1 - - [04/Jan/2022:00:58:33 +0000] "POST /api/heartbeat HTTP/1.0" 201 27
47.101.200.243 - - [04/Jan/2022:01:12:02 +0000] "GET / HTTP/1.1" 200 5330
47.101.200.243 - - [04/Jan/2022:01:12:03 +0000] "GET /assets/images/ghicon.svg HTTP/1.1" 200 1918
47.101.200.243 - - [04/Jan/2022:01:12:03 +0000] "GET /assets/images/screenshot.png HTTP/1.1" 200 38639
172.17.0.1 - - [04/Jan/2022:01:36:18 +0000] "POST /api/heartbeat HTTP/1.0" 201 27
47.101.200.178 - - [04/Jan/2022:02:04:16 +0000] "GET / HTTP/1.1" 200 5330
47.101.200.178 - - [04/Jan/2022:02:04:17 +0000] "GET /assets/images/screenshot.png HTTP/1.1" 200 38639
47.101.200.178 - - [04/Jan/2022:02:04:17 +0000] "GET /assets/images/ghicon.svg HTTP/1.1" 200 1918
172.17.0.1 - - [04/Jan/2022:02:12:54 +0000] "GET / HTTP/1.0" 200 5330
172.17.0.1 - - [04/Jan/2022:02:12:54 +0000] "GET / HTTP/1.0" 200 5330
panic: reflect: Call using zero Value argument

goroutine 64 [running]:
reflect.Value.call(0xbee3e0, 0xc0003e7a30, 0x13, 0xcda29f, 0x4, 0xc00000e820, 0x1, 0x1, 0xc00046cc90, 0x44a81c, ...)
	/usr/local/go/src/reflect/value.go:385 +0x14f8
reflect.Value.Call(0xbee3e0, 0xc0003e7a30, 0x13, 0xc00000e820, 0x1, 0x1, 0x453368, 0x907fba06b6d666, 0x8005f5c)
	/usr/local/go/src/reflect/value.go:321 +0xb4
github.com/jasonlvhit/gocron.callJobFuncWithParams(0xbee3e0, 0xc0003e7a30, 0xc0003e7a40, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/jasonlvhit/gocron@v0.0.0-20191106203602-f82992d443f4/gocron.go:141 +0x202
github.com/jasonlvhit/gocron.(*Job).run(0xc000409220, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/jasonlvhit/gocron@v0.0.0-20191106203602-f82992d443f4/gocron.go:127 +0x255
github.com/jasonlvhit/gocron.(*Scheduler).RunPending(0xc0001aa000)
	/go/pkg/mod/github.com/jasonlvhit/gocron@v0.0.0-20191106203602-f82992d443f4/gocron.go:530 +0xa0
github.com/jasonlvhit/gocron.(*Scheduler).Start.func1(0xc0003fcc80, 0xc0001aa000, 0xc00005d490)
	/go/pkg/mod/github.com/jasonlvhit/gocron@v0.0.0-20191106203602-f82992d443f4/gocron.go:619 +0x42
created by github.com/jasonlvhit/gocron.(*Scheduler).Start
	/go/pkg/mod/github.com/jasonlvhit/gocron@v0.0.0-20191106203602-f82992d443f4/gocron.go:615 +0x87
```

**Comment by muety** [comment]
You're using quite an out-dated version of Wakapi. I think I can remember to having fixed this bug in the mean time. Could you try upgrading to the latest version, please? Don't forget to backup your database before, just in case.

**Comment by muety** [comment]
Were you able to get around this using a more recent version?
