### ISSUE TITLE
Heartbeats hash is failing null constraint

### ISSUE THREAD

**Issue by NickAcPT** [muety/wakapi#352]
**Describe the bug**
For some reason, I am getting the following error:

<details>
<summary>WakAPI log</summary>

```
2022-04-10T23:31:58.89729+01:00 [WARN ] with sqlite, only a single connection is supported
2022-04-10T23:31:58.899104+01:00 [INFO ] potentially running migration '20201103-rename_language_mappings_table'
2022-04-10T23:31:58.8996162+01:00 [INFO ] potentially running migration '20201106-migration_cascade_constraints'
2022-04-10T23:31:58.8996162+01:00 [INFO ] not attempting to drop and regenerate constraints on sqlite
2022-04-10T23:31:58.8996162+01:00 [INFO ] potentially running migration '20210202-fix_cascade_for_alias_user_constraint'
2022-04-10T23:31:58.900228+01:00 [INFO ] not attempting to drop and regenerate constraints on sqlite
2022-04-10T23:31:58.900228+01:00 [INFO ] potentially running migration '20220403-drop_user_project_idx'
2022-04-10T23:32:00.5021276+01:00 [ERROR] UNIQUE constraint failed: heartbeats.hash
panic: UNIQUE constraint failed: heartbeats.hash

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc00020c000?, {0xc000344030?, 0xc000344030?}, {0x0?, 0x0?, 0x0?})
        C:/Users/runneradmin/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:57 +0x3f
github.com/emvi/logbuch.(*Logger).Fatal(0xc00020c000, {0xc000344030, 0x29}, {0x0, 0x0, 0x0})
        C:/Users/runneradmin/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x77
github.com/emvi/logbuch.Fatal(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
github.com/muety/wakapi/migrations.RunSchemaMigrations(0x0?, 0x0?)
        D:/a/wakapi/wakapi/migrations/migrations.go:39 +0x75
github.com/muety/wakapi/migrations.Run(0xc000216d00?, 0x1?)
        D:/a/wakapi/wakapi/migrations/migrations.go:33 +0x34
main.main()
        D:/a/wakapi/wakapi/main.go:141 +0x4fa
```

</details>

I don't remember ever messing with the database to mess with the hashes, but there's a bunch of old rows that are null.
![](https://i.imgur.com/vtwdd3w.png)

**System information**
Please provide information on:
* Wakapi version: Upgrade from an unknown version to 2.3.3, although I know I did skip 2.3.2
* Operating system:  Windows 10 21H2 (19044.1586)
* Database: SQLite

**Comment by muety** [comment]
Hey, thanks for reporting this and sorry for the inconveniences. I'm still trying to make sense of this error. `null` in the `hash` column shouldn't be a problem, as in all databases supported by Wakapi (MySQL, Postgres, SQLite) [`null` values are considered unique](https://sqlite.org/nulls.html). I also couldn't reproduce that issue.

Can you please post the output of the following query? 

```sql
SELECT
    hash,
    COUNT(hash)
FROM
    heartbeats
GROUP BY hash
HAVING COUNT(hash) > 1;
```

As a workaround, you can probably set `automigrate_fail_silently` to `true`, but of course that won't actually solve the problem.

**Comment by NickAcPT** [comment]
> Hey, thanks for reporting this and sorry for the inconveniences. I'm still trying to make sense of this error. `null` in the `hash` column shouldn't be a problem, as in all databases supported by Wakapi (MySQL, Postgres, SQLite) [`null` values are considered unique](https://sqlite.org/nulls.html). I also couldn't reproduce that issue.
> 
> Can you please post the output of the following query?
> 
> ```sql
> SELECT
>     hash,
>     COUNT(hash)
> FROM
>     heartbeats
> GROUP BY hash
> HAVING COUNT(hash) > 1;
> ```
> 
> As a workaround, you can probably set `automigrate_fail_silently` to `true`, but of course that won't actually solve the problem.

@muety Apologies for not replying sooner.
Here's the result that I got:
| hash | COUNT\(hash\) |
| :--- | :--- |
| 103af4afcd5614f8 | 2 |

After digging for a bit, it appears that I did, in fact, have a duplicate heartbeat in the database somehow.

| id | time | created\_at | hash |
| :--- | :--- | :--- | :--- |
| 397833 | 2022-04-07 10:00:13.764+01:00 | 2022-04-07 10:07:45.657+01:00 | 103af4afcd5614f8 |
| 397867 | 2022-04-07 10:00:13.764+01:00 | 2022-04-07 10:07:56.657+01:00 | 103af4afcd5614f8 |

I'm assuming that the way to fix it is by either dropping one of these heartbeats or just generating a new random hash for both.

Assuming nothing breaks, I opted for using the latter in my local database.
```sql
update heartbeats
set hash = lower(hex(randomblob(8)))
where hash = '103af4afcd5614f8';
```
