### ISSUE TITLE
 Referencing column 'summary_id' and referenced column 'id' in foreign key constraint 'fk_summaries_editors' are incompatible.

### ISSUE THREAD

**Issue by shyim** [muety/wakapi#416]
**Describe the bug**
I tried to upgrade my instance from 2.3.4 to 2.4.0 and the migration failed

```
Waiting for database to come up
wait-for-it.sh: waiting 60 seconds for mysql:3306
wait-for-it.sh: mysql:3306 is available after 2 seconds
2022-10-02T08:18:45.811234694Z [INFO ] potentially running migration '20201103-rename_language_mappings_table'
2022-10-02T08:18:45.820376339Z [INFO ] potentially running migration '20201106-migration_cascade_constraints'
2022-10-02T08:18:45.835806616Z [INFO ] no need to migrate '20201106-migration_cascade_constraints'
2022-10-02T08:18:45.835826585Z [INFO ] potentially running migration '20210202-fix_cascade_for_alias_user_constraint'
2022-10-02T08:18:45.839379376Z [INFO ] no need to migrate '20210202-fix_cascade_for_alias_user_constraint'
2022-10-02T08:18:45.839399756Z [INFO ] potentially running migration '20220403-drop_user_project_idx'
2022-10-02T08:18:45.842158447Z [INFO ] no need to migrate '20220403-drop_user_project_idx'
2022-10-02T08:18:45.842174533Z [INFO ] potentially running migration '20220930-drop_heartbeats_entity_idx'
2022-10-02T08:19:03.329885472Z [ERROR] Error 3780: Referencing column 'summary_id' and referenced column 'id' in foreign key constraint 'fk_summaries_editors' are incompatible.
panic: Error 3780: Referencing column 'summary_id' and referenced column 'id' in foreign key constraint 'fk_summaries_editors' are incompatible.
goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc000164380?, {0xc0000f5290?, 0xc0000f5290?}, {0x0?, 0x0?, 0x0?})
        /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:57 +0x3f
github.com/emvi/logbuch.(*Logger).Fatal(0xc000164380, {0xc0000f5290, 0x89}, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x77
github.com/emvi/logbuch.Fatal(...)
        /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
github.com/muety/wakapi/migrations.RunSchemaMigrations(0x0?, 0x0?)
        /src/migrations/migrations.go:39 +0x75
github.com/muety/wakapi/migrations.Run(0xc00010b1e0?, 0x2?)
        /src/migrations/migrations.go:33 +0x34
main.main()
        /src/main.go:152 +0x5a5
```

**System information**
Please provide information on:
* Wakapi version: 2.3.4 -> 2.4.0
* Operating system
    * Docker: latest tag
* Database MySQL 8

**Comment by shyim** [comment]
I upgraded now to 2.3.8. Still crashes trying from there to 2.4.0

**Comment by muety** [comment]
Hi @shyim, sorry for the inconveniences! For helping me debugging this, could you please try to run the following two SQL queries and post their outputs?

```sql
SHOW CREATE TABLE summaries;
SHOW CREATE TABLE summary_items;
```

**Comment by shyim** [comment]
Hey,

no problem :)

```
CREATE TABLE `summaries` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` varchar(191) NOT NULL,
  `from_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `to_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `num_heartbeats` bigint DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_time_summary_user` (`user_id`,`from_time`,`to_time`),
  CONSTRAINT `fk_summaries_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1070 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
```

```
CREATE TABLE `summary_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `summary_id` bigint unsigned DEFAULT NULL,
  `type` tinyint unsigned DEFAULT NULL,
  `key` longtext,
  `total` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_type` (`type`),
  KEY `fk_summaries_machines` (`summary_id`),
  CONSTRAINT `fk_summaries_editors` FOREIGN KEY (`summary_id`) REFERENCES `summaries` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_summaries_languages` FOREIGN KEY (`summary_id`) REFERENCES `summaries` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_summaries_machines` FOREIGN KEY (`summary_id`) REFERENCES `summaries` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_summaries_operating_systems` FOREIGN KEY (`summary_id`) REFERENCES `summaries` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_summaries_projects` FOREIGN KEY (`summary_id`) REFERENCES `summaries` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5899 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

**Comment by muety** [comment]
As a quick fix - until I push a permanent one - please try to run the following queries and then restart Wakapi once again:

```sql
alter table summary_items drop constraint `fk_summaries_editors`;
alter table summary_items drop constraint `fk_summaries_languages`;
alter table summary_items drop constraint `fk_summaries_machines`;
alter table summary_items drop constraint `fk_summaries_operating_systems`;
alter table summary_items drop constraint `fk_summaries_projects`;

alter table summary_items modify summary_id bigint unsigned null;
alter table summaries modify id bigint unsigned not null;
```

Quick background: the auto-migrator assumes the `summary.id` (and `summary_items.summary_id`) columns to be of type `int`. In your database, they're `bigint` for whatever reason. The above change will fix this.

I'm wondering if more people are having this issue? :thinking: If yes, please comment!

Sorry again...

**Comment by shyim** [comment]
works again :)

No problem. Project is open-source and free, it's nice to have this :)

**Comment by Skillkiller** [comment]
Hey,
I had to delete the following constrains:
````sql
ALTER TABLE `wakapi`.`summary_items` DROP FOREIGN KEY `fk_summary_items_summary`;
ALTER TABLE `wakapi`.`summary_items` DROP FOREIGN KEY `fk_summaries_labels`;
````

After that i changed the data types with your provided snippet:
````sql
alter table summary_items modify summary_id int unsigned null;
alter table summaries modify id int unsigned not null;
````

Thank you 👍

**Comment by Skillkiller** [comment]
For tracking:
I used Watchtower to update to the latest Docker image on 03.10.2022 at 08:00 German time. From which version I come exactly, I can not find out unfortunately but I pulled the latest image on 23.09.

Watchtower Log:
````
Watchtower updates on SK-08: Found new n1try/wakapi:latest image (5b4989305dd8)
Stopping /web-wakapi-1 (11fdf8f95422) with SIGTERM
Creating /web-wakapi-1
````

After this update I had the following error messages:
````
web-wakapi-1  | wait-for-it.sh: waiting 60 seconds for mysql:3306
web-wakapi-1  | wait-for-it.sh: mysql:3306 is available after 0 seconds
web-wakapi-1  | 2022-10-07T14:21:52.827632136Z [INFO ] potentially running migration '20201103-rename_language_mappings_table'
web-wakapi-1  | 2022-10-07T14:21:52.8292954Z [INFO ] potentially running migration '20201106-migration_cascade_constraints'
web-wakapi-1  | 2022-10-07T14:21:52.8310689Z [INFO ] no need to migrate '20201106-migration_cascade_constraints'
web-wakapi-1  | 2022-10-07T14:21:52.83107957Z [INFO ] potentially running migration '20210202-fix_cascade_for_alias_user_constraint'
web-wakapi-1  | 2022-10-07T14:21:52.83271961Z [INFO ] no need to migrate '20210202-fix_cascade_for_alias_user_constraint'
web-wakapi-1  | 2022-10-07T14:21:52.832729599Z [INFO ] potentially running migration '20220403-drop_user_project_idx'
web-wakapi-1  | 2022-10-07T14:21:52.834438719Z [INFO ] no need to migrate '20220403-drop_user_project_idx'
web-wakapi-1  | 2022-10-07T14:21:52.834451381Z [INFO ] potentially running migration '20220930-drop_heartbeats_entity_idx'
web-wakapi-1  | 2022-10-07T14:21:52.837956303Z [INFO ] potentially running migration '20221002-fix_summary_id_types'
web-wakapi-1  | 2022-10-07T14:21:52.847260877Z [ERROR] migration '20221002-fix_summary_id_types' failed - Error 3780: Referencing column 'summary_id' and referenced column 'id' in foreign key constraint 'fk_summaries_labels' are incompatible.
web-wakapi-1  | panic: migration '20221002-fix_summary_id_types' failed - Error 3780: Referencing column 'summary_id' and referenced column 'id' in foreign key constraint 'fk_summaries_labels' are incompatible.
web-wakapi-1  |
web-wakapi-1  | goroutine 1 [running]:
web-wakapi-1  | github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc000161000?, {0xeefe50?, 0xeefe50?}, {0xc000c556c0?, 0xc000c556c0?, 0x2?})
web-wakapi-1  |         /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:59 +0x67
web-wakapi-1  | github.com/emvi/logbuch.(*Logger).Fatal(0xc000161000, {0xeefe50, 0x1a}, {0xc000c556c0, 0x2, 0x2})
web-wakapi-1  |         /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x77
web-wakapi-1  | github.com/emvi/logbuch.Fatal(...)
web-wakapi-1  |         /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
web-wakapi-1  | github.com/muety/wakapi/migrations.RunPreMigrations(0x0?, 0x0?)
web-wakapi-1  |         /src/migrations/migrations.go:49 +0x228
web-wakapi-1  | github.com/muety/wakapi/migrations.Run(0xc00068c9c0?, 0x3?)
web-wakapi-1  |         /src/migrations/migrations.go:32 +0x25
web-wakapi-1  | main.main()
web-wakapi-1  |         /src/main.go:154 +0x5a5
````

**Comment by muety** [comment]
Thanks for sharing this, @Skillkiller! I assume this was for the very latest Docker image, corresponding to Wakapi version 2.5.0?

I'll add these two statements to the migration file, just in case more people run into that same issue.

**Comment by Skillkiller** [comment]
> I assume this was for the very latest Docker image, corresponding to Wakapi version 2.5.0?

Yes, that's exactly how it is. I have updated to version 2.5.0.
Thanks for your fix.
