### ISSUE TITLE
docker-compose failed to start waka service

### ISSUE THREAD

**Issue by ookangzheng** [muety/wakapi#477]
**Describe the bug**
I print out the logs and got sqlite migration fail , update from version `2.6.1` to `2.7.0`

```
2023-04-02T14:34:55.593303947Z [INFO ] creating job queue 'wakapi.default' (1 workers)
2023-04-02T14:34:55.629601224Z [INFO ] creating job queue 'wakapi.processing' (1 workers)
2023-04-02T14:34:55.630113909Z [INFO ] creating job queue 'wakapi.reports' (1 workers)
2023-04-02T14:34:55.630365064Z [INFO ] creating job queue 'wakapi.mail' (1 workers)
2023-04-02T14:34:55.630554673Z [INFO ] creating job queue 'wakapi.imports' (1 workers)
2023-04-02T14:34:55.630744073Z [INFO ] creating job queue 'wakapi.housekeeping' (1 workers)
2023-04-02T14:34:55.696276686Z [INFO ] disabling data retention policy, keeping data forever
2023-04-02T14:34:55.696325312Z [WARN ] with sqlite, only a single connection is supported
2023-04-02T14:34:55.696414158Z [INFO ] starting with sqlite3 database
2023-04-02T14:34:55.698921096Z [INFO ] potentially running migration '20201103-rename_language_mappings_table'
2023-04-02T14:34:55.700966532Z [INFO ] potentially running migration '20201106-migration_cascade_constraints'
2023-04-02T14:34:55.701007458Z [INFO ] not attempting to drop and regenerate constraints on sqlite
2023-04-02T14:34:55.701013011Z [INFO ] potentially running migration '20210202-fix_cascade_for_alias_user_constraint'
2023-04-02T14:34:55.701020128Z [INFO ] not attempting to drop and regenerate constraints on sqlite
2023-04-02T14:34:55.701024374Z [INFO ] potentially running migration '20220403-drop_user_project_idx'
2023-04-02T14:34:55.702067049Z [INFO ] no need to migrate '20220403-drop_user_project_idx'
2023-04-02T14:34:55.702107212Z [INFO ] potentially running migration '20220930-drop_heartbeats_entity_idx'
2023-04-02T14:34:55.704167274Z [INFO ] potentially running migration '20221002-fix_summary_id_types'
2023-04-02T14:34:55.704203336Z [INFO ] potentially running migration '20221028-fix_heartbeats_time_user_idx'
2023-04-02T14:34:55.707395097Z [ERROR] attempt to write a readonly database (8)
panic: attempt to write a readonly database (8)

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc000156c80?, {0xc000bc5680?, 0xc000bc5680?}, {0x0?, 0x0?, 0x0?})
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:57 +0x3f
github.com/emvi/logbuch.(*Logger).Fatal(0xc000156c80, {0xc000bc5680, 0x28}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x77
github.com/emvi/logbuch.Fatal(...)
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
github.com/muety/wakapi/migrations.RunSchemaMigrations(0x0?, 0x0?)
	/src/migrations/migrations.go:81 +0x65
github.com/muety/wakapi/migrations.Run(0xc000091860?, 0x1?)
	/src/migrations/migrations.go:75 +0x34
main.main()
	/src/main.go:154 +0x71d

```

**System information**
Please provide information on:
* Wakapi version: `2.7.0`
* Operating system
    * If Linux: Debian 11
    * If Docker: `ghcr.io/muety/wakapi:latest`
* Database: `sqlite`

**Comment by muety** [comment]
Can you show your compose file, please?

**Comment by YC** [comment]
Possible duplicate of #471

**Comment by ookangzheng** [comment]
> Possible duplicate of #471

It does fix my problem.

Thanks
