### ISSUE TITLE
Relay heartbeats to wakatime error executing relayed request

### ISSUE THREAD

**Issue by uiopak** [muety/wakapi#98]
After configuring WakaTime integration `wakapi` docker container crash:

```
172.17.0.1 - - [24/Jan/2021:13:37:45 +0000] "POST /api/heartbeat HTTP/1.1" 201 27
2021/01/24 13:37:45 error executing relayed request – Post "https://wakatime.com/api/v1/users/current/heartbeats.bulk": x509: certificate signed by unknown authority
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xada8cd]
goroutine 109 [running]:
github.com/muety/wakapi/middlewares/custom.(*WakatimeRelayMiddleware).send(0xc000010128, 0xcf2ae9, 0x4, 0xd17ba6, 0x39, 0xe02180, 0xc000342030, 0xc00043ff80)
/src/middlewares/custom/wakatime.go:94 +0x3ad
created by github.com/muety/wakapi/middlewares/custom.(*WakatimeRelayMiddleware).ServeHTTP
/src/middlewares/custom/wakatime.go:69 +0x8a5
```

When I run from source everything works.

**Comment by muety** [comment]
Thanks for bringing this up! I'll investigate later.

**Comment by muety** [comment]
Should be fixed now, please check again. Keep in mind that DockerHub takes quite some time to rebuild the image.
